const plantDatabase = [
    {
        "id": 1,
        "name": "פילודנדרון פינק פרינסס",
        "scientificName": "Philodendron erubescens",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח טרופי מיערות קולומביה שזכה לפופולריות רבה בזכות עליו הוורודים.",
        "uses": "צמח נוי ביתי מבוקש מאוד.",
        "soil": "תערובת עציצים מנוקזת היטב ואוורירית.",
        "propagation": "ייחורי גבעול עם שורשי אוויר.",
        "tip": "שמרו על לחות גבוהה לקבלת צבעים עזים.",
        "icon": "🪴",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Philodendron_erubescens_-_Leaves.jpg/960px-Philodendron_erubescens_-_Leaves.jpg",
        "health": "רעיל לבליעה לחיות מחמד ובני אדם (מכיל קריסטלים של אוקסלט הסידן). מגע עם המוהל עלול לגרות את העור."
    },
    {
        "id": 2,
        "name": "מונסטרה אדנסוני (מגוונת)",
        "scientificName": "Monstera adansonii",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 2,
        "history": "ילידת מרכז ודרום אמריקה. זן נדיר עם כתמים לבנים.",
        "uses": "טיפוס על עמוד טחב או צמח משתפל.",
        "soil": "אדמה עשירה בחומר אורגני.",
        "propagation": "ייחורים במים.",
        "tip": "דורש יותר אור מזנים רגילים בשל החלקים הלבנים נטולי הכלורופיל.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Monstera_adansonii_79319231.jpg/960px-Monstera_adansonii_79319231.jpg",
        "health": "מטהר אוויר מזיהומים קלים, אך רעיל לבליעה (אוקסלט הסידן). יש להרחיק מכלבים וחתולים."
    },
    {
        "id": 3,
        "name": "ציפור גן עדן",
        "scientificName": "Strelitzia reginae",
        "family": "סטרליציים",
        "category": "נפוץ",
        "water": 3,
        "sun": 3,
        "history": "מקורו בדרום אפריקה, נקרא על שם פרחיו המזכירים ציפור צבעונית.",
        "uses": "גינון חוץ ופנים, פרחי קטיף.",
        "soil": "אדמה כבדה ועשירה.",
        "propagation": "חלוקת שורשים.",
        "tip": "צמח בוגר (בן 4-5 שנים) נדרש כדי להפריח.",
        "icon": "🌺",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Bird_of_Paradise_flower.JPG/960px-Bird_of_Paradise_flower.JPG",
        "health": "רעיל קלות לחיות מחמד במקרה של אכילת העלים או הפרחים (גורם להקאות)."
    },
    {
        "id": 4,
        "name": "ורד המדבר",
        "scientificName": "Adenium obesum",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "מקורו באזורים הצחיחים של אפריקה וחצי האי ערב.",
        "uses": "צמח בונסאי פופולרי.",
        "soil": "תערובת קקטוסים סופר-מנוקזת.",
        "propagation": "זרעים או ייחורים.",
        "tip": "היזהרו מהמוהל החלבי - הוא רעיל.",
        "icon": "🏜️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg/960px-Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg",
        "health": "רעיל מאוד! המוהל החלבי מכיל רעלנים הפוגעים בלב. השתמשו בכפפות בעת הגיזום."
    },
    {
        "id": 5,
        "name": "מימוזה ביישנית",
        "scientificName": "Mimosa pudica",
        "family": "קטניות",
        "category": "נדיר",
        "water": 3,
        "sun": 3,
        "history": "צמח מיוחד מדרום ומרכז אמריקה שעליו נסגרים במגע.",
        "uses": "צמח חינוכי לילדים וחובבי בוטניקה.",
        "soil": "אדמה לחה ומנוקזת.",
        "propagation": "זריעה מזרעים.",
        "tip": "אל תגעו בעלים יותר מדי, זה גוזל מהצמח אנרגיה.",
        "icon": "🌱",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Mimosa_pudica_in_September_month.jpg/960px-Mimosa_pudica_in_September_month.jpg",
        "health": "בטוח יחסית, אך מכיל אלקלואידים בכמויות קטנות. ברפואה המסורתית ההודית משמש לריפוי פצעים."
    },
    {
        "id": 6,
        "name": "ענב ורוד (מדינילה מרהיבה)",
        "scientificName": "Medinilla magnifica",
        "family": "מלסטומיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "אפיפיט טרופי מהפיליפינים. שימש כפרח מלכותי בבלגיה.",
        "uses": "צמח בית יוקרתי.",
        "soil": "אדמת סחלבים קלה.",
        "propagation": "ייחורים בתנאי לחות קיצוניים.",
        "tip": "צריך לחות מאוד גבוהה כדי לפרוח.",
        "icon": "🍇",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Medinilla_magnifica_flor.jpg/960px-Medinilla_magnifica_flor.jpg",
        "health": "נחשב בטוח ולא רעיל לחיות מחמד ולבני אדם."
    },
    {
        "id": 7,
        "name": "אלוורה",
        "scientificName": "Aloe vera",
        "family": "שושניים",
        "category": "נפוץ",
        "water": 1,
        "sun": 3,
        "history": "צמח עתיק ששימש תרבויות רבות למטרות רפואיות.",
        "uses": "ריפוי כוויות וטיפוח העור.",
        "soil": "תערובת קקטוסים מחולחלת.",
        "propagation": "הפרדת חוטרים.",
        "tip": "אל תשקו לעיתים קרובות, במיוחד בחורף.",
        "icon": "🌵",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/960px-Aloe_vera_flower_inset.png",
        "health": "ידוע בסגולותיו לריפוי כוויות, הרגעת העור וטיפוח. הקליפה החיצונית מכילה אלואין, שעלול להיות רעיל לחיות מחמד."
    },
    {
        "id": 8,
        "name": "פוטוס זהוב",
        "scientificName": "Epipremnum aureum",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 1,
        "history": "יליד איי שלמה, אחד מצמחי הבית העמידים ביותר.",
        "uses": "טיהור אוויר ועיצוב פנים.",
        "soil": "כל אדמת עציצים סטנדרטית.",
        "propagation": "ייחורי מים קלים במיוחד.",
        "tip": "הוא יכול לשרוד כמעט בחושך מוחלט, אך יאבד מגוונו.",
        "icon": "🍃",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg/960px-Money_Plant_%28Epipremnum_aureum%29_4.jpg",
        "health": "מטהר אוויר מצוין (מסנן פורמלדהיד וקסילן), אך רעיל לחיות מחמד בשל קריסטלי סידן אוקסלט."
    },
    {
        "id": 9,
        "name": "דיונאה (מלכודת זבובים)",
        "scientificName": "Dionaea muscipula",
        "family": "טלליתיים",
        "category": "טורף",
        "water": 3,
        "sun": 3,
        "history": "צמח טורף מצפון אמריקה שפיתח מנגנון לכידה אקטיבי עקב מחסור בנוטריינטים בקרקע.",
        "uses": "צמח נוי והדברת חרקים טבעית.",
        "soil": "כבול טהור מעורבב עם פרלייט.",
        "propagation": "חלוקת שורשים באביב.",
        "tip": "השתמשו רק במים מזוקקים או מי גשמים, מים רגילים יהרגו אותו.",
        "icon": "🪰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Venus_Flytrap_showing_trigger_hairs.jpg/960px-Venus_Flytrap_showing_trigger_hairs.jpg",
        "health": "בטוח לחלוטין לחיות מחמד. לא ידוע על שימושים רפואיים."
    },
    {
        "id": 10,
        "name": "כדנית",
        "scientificName": "Nepenthes",
        "family": "כדניתיים",
        "category": "טורף",
        "water": 3,
        "sun": 2,
        "history": "צמחים טרופיים בעלי מלכודות בצורת כדים המכילים נוזל עיכול.",
        "uses": "צמח בית אקזוטי ייחודי.",
        "soil": "תערובת אוורירית של ספגנום ופרלייט.",
        "propagation": "ייחורי גבעול.",
        "tip": "שמרו על לחות אוויר גבוהה מאוד סביב הכדים.",
        "icon": "🏺",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/12/N.macrophylla_x_lowii.jpg",
        "health": "בטוח לחיות מחמד. נוזל הכד שימש בעבר ברפואה העממית באסיה לטיפול בבעיות עיכול, אך לא מומלץ לשימוש מודרני."
    },
    {
        "id": 11,
        "name": "סחלב פלנופסיס",
        "scientificName": "Phalaenopsis",
        "family": "סחלביים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "הסחלב הפופולרי ביותר בעולם, יליד דרום-מזרח אסיה.",
        "uses": "צמח מתנה קלאסי לבית.",
        "soil": "תערובת קליפות עץ וטחב מיוחדת לסחלבים.",
        "propagation": "קיקי (שתילי אוויר).",
        "tip": "אל תתנו למים לעמוד בכתר העלים כדי למנוע ריקבון.",
        "icon": "🌸",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg",
        "health": "בטוח לחלוטין ולא רעיל לכלבים, חתולים וילדים."
    },
    {
        "id": 12,
        "name": "עץ הבוקן (בונסאי)",
        "scientificName": "Ficus retusa",
        "family": "תותיים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "עץ פיקוס אסיאתי המשמש רבות לאמנות הבונסאי היפנית.",
        "uses": "אמנות בונסאי ועיצוב פנים מינימליסטי.",
        "soil": "אדמת בונסאי מנקזת היטב.",
        "propagation": "ייחורים באביב.",
        "tip": "גזמו באופן קבוע כדי לשמור על צורת העץ המיניאטורי.",
        "icon": "🌳",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ficus_retusa_herbarium_sheet.jpg/960px-Ficus_retusa_herbarium_sheet.jpg",
        "health": "המוהל החלבי עלול לגרות את העור ורעיל לבליעה לחיות מחמד."
    },
    {
        "id": 13,
        "name": "בזילקום (ריחן)",
        "scientificName": "Ocimum basilicum",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 3,
        "sun": 3,
        "history": "צמח תבלין שהגיע במקור מהודו ונהיה סימן היכר של המטבח האיטלקי.",
        "uses": "בישול, פסטו, סלטים.",
        "soil": "אדמה עשירה וקלה.",
        "propagation": "זרעים.",
        "tip": "הסירו את הפרחים ברגע שהם מופיעים כדי לשמור על טעם העלים.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/960px-Ocimum_basilicum_8zz.jpg",
        "health": "אנטי-בקטריאלי, עשיר בנוגדי חמצון, ויטמין K וברזל. מצוין לבריאות הלב."
    },
    {
        "id": 14,
        "name": "נענע",
        "scientificName": "Mentha",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 3,
        "sun": 2,
        "history": "צמח תבלין מרענן המשמש לחליטות מזה אלפי שנים במזרח התיכון.",
        "uses": "תה, קוקטיילים, תיבול.",
        "soil": "אדמה לחה באופן קבוע.",
        "propagation": "שלוחות שורש.",
        "tip": "מומלץ לגדל בעציץ נפרד, אחרת היא תשתלט על כל הגינה.",
        "icon": "🌱",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Mentha_spicata-IMG_6186.jpg/960px-Mentha_spicata-IMG_6186.jpg",
        "health": "מרגיע את מערכת העיכול, מקל על כאבי ראש ומיגרנות, ומשפר ריכוז."
    },
    {
        "id": 15,
        "name": "סנסיווריה (לשון החותנת)",
        "scientificName": "Sansevieria trifasciata",
        "family": "אספרגיים",
        "category": "נפוץ",
        "water": 1,
        "sun": 1,
        "history": "צמח מערב אפריקאי שנחשב לאחד מצמחי הבית החזקים ביותר.",
        "uses": "מטהר אוויר מצוין לפי מחקר של נאס\"א.",
        "soil": "תערובת קקטוסים.",
        "propagation": "חלוקה או חיתוך עלים.",
        "tip": "הדרך הכי קלה להרוג סנסיווריה היא להשקות אותה יותר מדי.",
        "icon": "🐍",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/960px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg",
        "health": "מטהר אוויר מעולה, פולט חמצן בלילה (מצוין לחדרי שינה). רעיל קלות לחיות מחמד."
    },
    {
        "id": 16,
        "name": "זמיוקולקס",
        "scientificName": "Zamioculcas zamiifolia",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 1,
        "sun": 1,
        "history": "יליד מזרח אפריקה, הובא לאירופה בשנות ה-90 והפך ללהיט מיידי.",
        "uses": "צמח משרד קלאסי ומושלם למתחילים.",
        "soil": "תערובת מנוקזת היטב.",
        "propagation": "הפרדת פקעות או ייחורי עלים (תהליך איטי جدا).",
        "tip": "מעדיף הזנחה. תשקו רק כשהאדמה יבשה לחלוטין לחלוטין.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Zamioculcas_zamiifolia_1.jpg/960px-Zamioculcas_zamiifolia_1.jpg",
        "health": "רעיל לבליעה (קריסטלי אוקסלט הסידן). יש לשטוף ידיים לאחר מגע עם מוהל הצמח."
    },
    {
        "id": 17,
        "name": "קרסולה צורנית (עץ הכסף)",
        "scientificName": "Crassula ovata",
        "family": "טבוריתיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט מדרום אפריקה שנחשב כמביא מזל ועושר בפנג שואי.",
        "uses": "צמח נוי עמיד לבית ולגינה.",
        "soil": "אדמת סוקולנטים מחולחלת.",
        "propagation": "ייחורי גבעול או עלים.",
        "tip": "עליו מקבלים קצוות אדמדמים בחשיפה רבה לשמש.",
        "icon": "💰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Crassula_ovata_700.jpg",
        "health": "רעיל לכלבים וחתולים (גורם לדיכאון והקאות)."
    },
    {
        "id": 18,
        "name": "פיקוס כינורי",
        "scientificName": "Ficus lyrata",
        "family": "תותיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 3,
        "history": "עץ יער גשם מאפריקה בעל עלים גדולים בצורת כינור, פופולרי מאוד בעיצוב מודרני.",
        "uses": "צמח עציץ רצפתי דומיננטי.",
        "soil": "תערובת אוורירית ועשירה.",
        "propagation": "ייחורי אוויר.",
        "tip": "רגיש לשינויי מיקום ורוחות פרצים, העלים עלולים לנשור.",
        "icon": "🎻",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Starr_031108-0130_Ficus_lyrata.jpg/960px-Starr_031108-0130_Ficus_lyrata.jpg",
        "health": "מוהל הצמח רעיל ועלול לגרום לגירוי בעור ולבעיות עיכול אם נבלע."
    },
    {
        "id": 19,
        "name": "שרך קן-הציפור",
        "scientificName": "Asplenium nidus",
        "family": "אספלניים",
        "category": "שרך",
        "water": 3,
        "sun": 2,
        "history": "אפיפיט טרופי הגדל על צמרות עצים ויוצר צורת שושנה ענקית.",
        "uses": "צמח בית ירוק ומבריק.",
        "soil": "אדמה שומרת לחות אך לא בוצית.",
        "propagation": "נבגים (קשה מאוד בתנאי בית).",
        "tip": "אל תגעו בעלים הצעירים והרכים שצומחים מהמרכז, הם שבירים מאוד.",
        "icon": "🪹",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg/960px-Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg",
        "health": "בטוח לחלוטין ולא רעיל. עוזר בהעלאת לחות האוויר בבית."
    },
    {
        "id": 20,
        "name": "אדניום כפול (ורד המדבר פרח מלא)",
        "scientificName": "Adenium obesum flore pleno",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "פיתוח בוטני מודרני מטאיוואן של ורד המדבר הקלאסי עם פרחים מלאים ועשירים.",
        "uses": "צמח אספנים מרשים.",
        "soil": "מצע קקטוסים אוורירי.",
        "propagation": "הרכבות (לשמירת גנטיקת הפרח).",
        "tip": "דורש דישון קבוע בעונת הצמיחה כדי לתמוך בפרחים הענקיים.",
        "icon": "🌹",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg/960px-Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg",
        "health": "רעיל מאוד בדומה לוורד המדבר הרגיל. הרחיקו מהישג ידם של ילדים."
    },
    {
        "id": 21,
        "name": "אגבה רכה",
        "scientificName": "Agave attenuata",
        "family": "אספרגיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "זן אגבה מקסיקני ללא קוצים, בניגוד לרוב אחיה.",
        "uses": "גינון יוקרתי, גינון יובשני.",
        "soil": "אדמה בעלת ניקוז מהיר.",
        "propagation": "חוטרים בבסיס הצמח.",
        "tip": "מושלמת לאזורים ציבוריים מכיוון שאינה דוקרת.",
        "icon": "🌵",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Agave_attenuata_001.JPG/960px-Agave_attenuata_001.JPG",
        "health": "המוהל עלול לגרות את העור ולגרום לדלקת מגע. פחות מסוכן מאגבות עם קוצים, אך עדיין דורש זהירות."
    },
    {
        "id": 22,
        "name": "מונסטרה דליציוסה",
        "scientificName": "Monstera deliciosa",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "הצמח הטרופי המפורסם בעולם, בעל העלים המחוררים שנועדו לעמוד ברוחות עזות.",
        "uses": "עיצוב פנים טרופי.",
        "soil": "מצע עציצים רגיל עם תוספת קוקוס ופרלייט.",
        "propagation": "ייחורים עם שורשי אוויר.",
        "tip": "נקו את העלים הגדולים מאבק עם מטלית לחה מדי פעם.",
        "icon": "🌴",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/960px-Monstera_deliciosa2.jpg",
        "health": "הפירות הבשלים אכילים (בטעם אננס-בננה), אך שאר חלקי הצמח רעילים לבליעה."
    },
    {
        "id": 23,
        "name": "קלתאה אורביפוליה",
        "scientificName": "Calathea orbifolia",
        "family": "מרנטתיים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 1,
        "history": "צמח טרופי מדרום אמריקה בעל עלים עגולים ענקיים עם פסים כסופים.",
        "uses": "הכנסת דרמה טרופית הביתה.",
        "soil": "אדמה שומרת לחות אך מנוקזת.",
        "propagation": "חלוקת שורשים.",
        "tip": "צמח תפילה - העלים זזים ונסגרים בלילה. רגיש מאוד ליובש ולמי ברז.",
        "icon": "🦓",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Calathea_orbifolia_2.jpg/960px-Calathea_orbifolia_2.jpg",
        "health": "בטוח לחלוטין ולא רעיל לחיות מחמד."
    },
    {
        "id": 24,
        "name": "אלוקסיה פולי",
        "scientificName": "Alocasia amazonica",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח היברידי עם עלים חצים דרמטיים דמויי פלסטיק מבריק.",
        "uses": "צמח אווירה דומיננטי.",
        "soil": "מצע תפוח ולח.",
        "propagation": "הפרדת פקעיות קטנות בשורשים.",
        "tip": "עלול להיכנס לתרדמת חורף ולהשיר את עליו, אל תזרקו - הפקעת חיה!",
        "icon": "🛡️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Alocasia_macrorrhiza_-_Val_Rahmeh_-_DSC04449.JPG/960px-Alocasia_macrorrhiza_-_Val_Rahmeh_-_DSC04449.JPG",
        "health": "רעיל מאוד לבליעה (סידן אוקסלט). גורם לנפיחות בפה ובגרון."
    },
    {
        "id": 25,
        "name": "ירקה מגוונת",
        "scientificName": "Chlorophytum comosum",
        "family": "אספרגיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "מצמחי הבית הוותיקים והאהובים ביותר. מייצר \"עכבישים\" קטנים בקצות הענפים.",
        "uses": "סלים תלויים.",
        "soil": "כל מצע יעבוד.",
        "propagation": "גזירה ושתילה של צמחי הבת (\"העכבישים\").",
        "tip": "עמיד גם בצל וגם בשמש חלקית. שורשיו הבשרניים אוגרים מים.",
        "icon": "🕷️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hierbabuena_0611_Revised.jpg/960px-Hierbabuena_0611_Revised.jpg",
        "health": "בטוח לחלוטין לחיות מחמד. צמח מטהר אוויר מהשורה הראשונה."
    },
    {
        "id": 26,
        "name": "שפלרה מוקרנת",
        "scientificName": "Schefflera actinophylla",
        "family": "קיסוסיים",
        "category": "עץ",
        "water": 2,
        "sun": 2,
        "history": "עץ אוסטרלי המוכר גם כעץ המטרייה בגלל סידור העלים.",
        "uses": "צמח רצפה ירוק נפח.",
        "soil": "מצע עציצים בסיסי.",
        "propagation": "ייחורים או זרעים.",
        "tip": "אפשר לגזום ללא פחד כדי ליצור מראה שיחי וצפוף.",
        "icon": "☂️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Octopus_Tree_%28Schefflera_actinophylla%29_at_Hyderabad%2C_AP_W_283.jpg",
        "health": "רעיל לחיות מחמד (עלול לגרום לגירוי חמור בפה ורעידות)."
    },
    {
        "id": 27,
        "name": "מרנטה לאוקונורה",
        "scientificName": "Maranta leuconeura",
        "family": "מרנטתיים",
        "category": "נדיר",
        "water": 3,
        "sun": 1,
        "history": "צמח קטן ומרהיב שמקפל את עליו בלילה כמו ידיים בתפילה.",
        "uses": "צמח שולחן מיוחד.",
        "soil": "אדמה עשירה בכבול.",
        "propagation": "חלוקה.",
        "tip": "דרושה לחות אוויר גבוהה. מצע יבש יגרום לקצוות העלים להשחים.",
        "icon": "🙏",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Maranta_leuconeura3.jpg",
        "health": "בטוח לחלוטין ואינו רעיל לילדים וחיות מחמד."
    },
    {
        "id": 28,
        "name": "הויה קרנוזה",
        "scientificName": "Hoya carnosa",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 2,
        "history": "צמח מטפס עם עלי שעווה עבים ופרחים מדהימים שנראים כמו כוכבי חרסינה.",
        "uses": "צמח משתפל או מטפס על סורג.",
        "soil": "מצע סחלבים אוורירי.",
        "propagation": "ייחורי גבעול ממושכים.",
        "tip": "אל תגזמו את העוקץ עליו פרח הצמח - באותו מקום תופיע הפריחה הבאה.",
        "icon": "⭐",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg/960px-NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg",
        "health": "בטוח לחלוטין ואינו רעיל."
    },
    {
        "id": 29,
        "name": "סטפנוטיס",
        "scientificName": "Stephanotis floribunda",
        "family": "הרדופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "יליד מדגסקר, ידוע בפרחיו הלבנים והריחניים המשמשים בזרות כלה.",
        "uses": "מטפס ריחני לבית ולמרפסת.",
        "soil": "אדמה מנקזת עשירה.",
        "propagation": "ייחורים למחצה-מעוצים.",
        "tip": "הפרחים מפיצים ריח יסמין חזק במיוחד בערב.",
        "icon": "👰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/31/Stephanotis_floribunda3L._Marie.jpg",
        "health": "בטוח לגידול בסביבת חיות מחמד וילדים."
    },
    {
        "id": 30,
        "name": "בגוניה מנוקדת",
        "scientificName": "Begonia maculata",
        "family": "בגוניים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח פוטוגני להפליא עם עלים בצורת כנף מלאך מנוקדים בנקודות כסף.",
        "uses": "צמח אספנים מעוצב.",
        "soil": "מצע עשיר שומר לחות.",
        "propagation": "ייחורי גבעול במים (מושרשים בקלות).",
        "tip": "מעדיף עציץ מעט צפוף ומים רק כשהחצי העליון של האדמה יבש.",
        "icon": "🎨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/df/Begonia_maculata3073316230.jpg",
        "health": "השורשים רעילים מאוד לחיות מחמד, גם העלים מכילים רעלנים המגרים את הפה."
    },
    {
        "id": 31,
        "name": "פיטוניה (צמח העצבים)",
        "scientificName": "Fittonia albivenis",
        "family": "קוציציים",
        "category": "נפוץ",
        "water": 3,
        "sun": 1,
        "history": "צמח זוחל מיערות פרו המוכר ברשת העורקים הלבנה או האדומה על עליו.",
        "uses": "טרריומים וגינות בקבוק.",
        "soil": "אדמה שומרת לחות קבועה.",
        "propagation": "ייחורים קטנים.",
        "tip": "מתעלף בדרמטיות כשהוא צמא, אך יחזור לעצמו במהירות לאחר השקיה.",
        "icon": "🧠",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Colpfl25.jpg/960px-Colpfl25.jpg",
        "health": "בטוח לחלוטין לחיות מחמד וילדים."
    },
    {
        "id": 32,
        "name": "פילאה פפרומיואידס",
        "scientificName": "Pilea peperomioides",
        "family": "סרפדיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח הפנקייק הסיני שכבש את העולם, קל לגידול ומתרבה במהירות.",
        "uses": "עציץ חלון מתוק לחלוקה לחברים.",
        "soil": "מצע עציצים רגיל.",
        "propagation": "מוציא אינספור פקעיות סביב צמח האם.",
        "tip": "סובבו את העציץ פעם בשבוע כדי שיגדל ישר ולא ייטה לכיוון השמש.",
        "icon": "🥞",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pilea_peperomioides_Chinese_money_plant.jpg/960px-Pilea_peperomioides_Chinese_money_plant.jpg",
        "health": "בטוח לחלוטין ולא רעיל."
    },
    {
        "id": 33,
        "name": "פלטיצריום (קרן האייל)",
        "scientificName": "Platycerium",
        "family": "פוליפודיים",
        "category": "שרך",
        "water": 2,
        "sun": 2,
        "history": "שרך אפיפיט יוצא דופן שעליו נראים כמו קרני אייל מפוצלות.",
        "uses": "תלייה על קירות כמיצג אמנות חי.",
        "soil": "טחב ספגנום לח, לעיתים מוצמד ללוח עץ.",
        "propagation": "חלוקת חוטרים בוגרים.",
        "tip": "השקו את הצמח דרך העלה המגן הבסיסי התחתון ולא ישירות על הקרניים.",
        "icon": "🦌",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Platycerium_bifurcatum.jpg/960px-Platycerium_bifurcatum.jpg",
        "health": "בטוח ואינו רעיל."
    },
    {
        "id": 34,
        "name": "טללית",
        "scientificName": "Drosera",
        "family": "טלליתיים",
        "category": "טורף",
        "water": 3,
        "sun": 3,
        "history": "צמח טורף עדין בעל זרועות דביקות המכוסות בטיפות המדמות טל.",
        "uses": "הדברת ברחשים וחרקים קטנים.",
        "soil": "מצע כבול.",
        "propagation": "זרעים קטנים או ייחורי עלים.",
        "tip": "כמו הדיונאה - רק מים מזוקקים ואור שמש חזק מאוד.",
        "icon": "💧",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Drosera_spatulata_KansaiHabit.jpg/960px-Drosera_spatulata_KansaiHabit.jpg",
        "health": "בטוח לחיות מחמד. ברפואה העממית שימש לטיפול בשיעול וברונכיט בשל חומרים מכייחים."
    },
    {
        "id": 35,
        "name": "פיקוס גומי",
        "scientificName": "Ficus elastica",
        "family": "תותיים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "עץ הודי חזק שבעבר הפיקו ממנו גומי טבעי.",
        "uses": "צמח רצפה גבוה לבית ולמשרד.",
        "soil": "מצע סטנדרטי מנוקז.",
        "propagation": "ייחורים.",
        "tip": "הזן השחור (Burgundy) צריך פחות אור, הזן המגוון (Tineke) צריך יותר.",
        "icon": "🌲",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ficus_elastica_leaves_02.JPG/960px-Ficus_elastica_leaves_02.JPG",
        "health": "המוהל הלבן (לייטקס) עלול לגרום לאלרגיות קשות בעור ולגירוי בעיניים."
    },
    {
        "id": 36,
        "name": "ליטופס (אבנים חיות)",
        "scientificName": "Lithops",
        "family": "חיעדיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט מדהים מדרום אפריקה שהתפתח להיראות כמו חלוקי נחל כדי להימנע מטורפים.",
        "uses": "אוסף מיוחד על אדן החלון.",
        "soil": "100% תערובת אבנים פומיס עם מעט מאוד חומר אורגני.",
        "propagation": "זרעים זעירים.",
        "tip": "משירים את עליהם פעם בשנה. בתקופה זו חל איסור מוחלט להשקות.",
        "icon": "🪨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Marloth-Lithops-drawing.jpg/960px-Marloth-Lithops-drawing.jpg",
        "health": "בטוח ואינו רעיל לחיות מחמד (אך חיות עלולות לאכול אותם בטעות כי הם נראים כמו אבנים)."
    },
    {
        "id": 37,
        "name": "טרדסקנטיה (יהודי נודד)",
        "scientificName": "Tradescantia zebrina",
        "family": "קומליניים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח משתפל עמיד בטירוף, עם עלים בגווני כסף וסגול נוצצים.",
        "uses": "סלים תלויים וצמח קל למתחילים.",
        "soil": "כל אדמה תתאים.",
        "propagation": "ייחורים פשוט משתרשים בכל מגע עם מים או אדמה.",
        "tip": "צבעו הסגול יהיה חזק יותר ככל שיקבל יותר אור (אך לא שמש ישירה קופחת).",
        "icon": "🌌",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Zebrina_pendula_20060521_2_closer.jpg",
        "health": "המוהל עלול לגרום לגירוי בעור אצל כלבים וחתולים במגע מתמשך."
    },
    {
        "id": 38,
        "name": "סטפליה (פרח הכוכב המסריח)",
        "scientificName": "Stapelia gigantea",
        "family": "הרדופיים",
        "category": "נדיר",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט קקטוס-לכאורה מדרום אפריקה שפורח בפרח ענק דמוי כוכב פרוותי.",
        "uses": "לאספנים הרפתקנים.",
        "soil": "תערובת קקטוסים.",
        "propagation": "ייחורי גבעול.",
        "tip": "הפרח מפיץ ריח של בשר רקוב כדי למשוך זבובים מאביקים.",
        "icon": "🌟",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Stapelia_gigantea00.jpg/960px-Stapelia_gigantea00.jpg",
        "health": "בטוח ואינו רעיל (הריח הרע מהפרח אינו מזיק בריאותית)."
    },
    {
        "id": 39,
        "name": "רוזמרין",
        "scientificName": "Rosmarinus officinalis",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 1,
        "sun": 3,
        "history": "שיח ים-תיכוני ארומטי בעל היסטוריה ארוכה ברפואה ובקולינריה.",
        "uses": "בישול בשרים, תפוחי אדמה, גדר חיה.",
        "soil": "אדמה גירית מנוקזת, עמיד לבצורת.",
        "propagation": "ייחורים חצי-מעוצים.",
        "tip": "לא אוהב עציצים קטנים לאורך זמן. חייב שמש מלאה בחוץ.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rosemary_in_bloom.JPG/960px-Rosemary_in_bloom.JPG",
        "health": "משפר זיכרון, אנטי-דלקתי, עשיר בנוגדי חמצון ומסייע לעיכול."
    },
    {
        "id": 40,
        "name": "עגבניית שרי",
        "scientificName": "Solanum lycopersicum var. cerasiforme",
        "family": "סולניים",
        "category": "ירק",
        "water": 3,
        "sun": 3,
        "history": "זן מתוק וקטן של עגבניה, שמקורו בדרום אמריקה וכיום פופולרי בגידול ביתי.",
        "uses": "סלטים ונשנוש ישר מהשיח.",
        "soil": "אדמה עשירה ודשנה מאוד.",
        "propagation": "זרעים.",
        "tip": "שתלו עמוק באדמה - הצמח מגדל שורשים לאורך כל הגבעול שקבור.",
        "icon": "🍅",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/960px-Tomato_je.jpg",
        "health": "הפרי בריא מאוד (מכיל ליקופן). העלים והגבעולים רעילים לאכילה (מכילים סולנין)."
    },
    {
        "id": 41,
        "name": "תות שדה",
        "scientificName": "Fragaria × ananassa",
        "family": "ורדיים",
        "category": "ירק",
        "water": 3,
        "sun": 3,
        "history": "הכלאה בוטנית של תותי בר מצפון ודרום אמריקה שנוצרה בצרפת.",
        "uses": "קינוחים וגידול מהנה לילדים.",
        "soil": "אדמה לחה ומנוקזת, רצוי לכסות בחיפוי קש.",
        "propagation": "שלוחות.",
        "tip": "הרחיקו את הפירות מאדמה לחה כדי שלא ירקבו.",
        "icon": "🍓",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/03/103_Fragaria_vesca_L.jpg",
        "health": "עשיר בוויטמין C ונוגדי חמצון. בטוח לחלוטין."
    },
    {
        "id": 42,
        "name": "ויקטוריה רג׳יה",
        "scientificName": "Victoria amazonica",
        "family": "נופריים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 3,
        "history": "שושנת המים הגדולה בעולם מהאמזונס, עליה יכולים לשאת משקל של ילד.",
        "uses": "בריכות נוי גדולות וגנים בוטניים.",
        "soil": "אדמה בוצית בקרקעית בריכה מחוממת.",
        "propagation": "זרעים בתנאים מיוחדים.",
        "tip": "הפרח פורח בלילה, לבן ביום הראשון וורוד ביום השני.",
        "icon": "🪷",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Victoria_amazonica_edit_1.jpg/960px-Victoria_amazonica_edit_1.jpg",
        "health": "הזרעים שימשו בעבר למאכל על ידי ילידים. הצמח עצמו מוגן בקוצים חדים כתער מתחת לעלים."
    },
    {
        "id": 43,
        "name": "עץ האהבה (אפרומיה)",
        "scientificName": "Peperomia obtusifolia",
        "family": "פלפליים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "דומה מאוד לפילאה אך עליו עבים וכהים יותר, מגיע מיערות הגשם בפלורידה והקריביים.",
        "uses": "צמח שולחן קומפקטי וסימפטי.",
        "soil": "אדמת עציצים מתנקזת.",
        "propagation": "ייחורי עלה או גבעול.",
        "tip": "האויב מספר 1 שלו הוא השקיית יתר.",
        "icon": "💚",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Peperomia_obtusifolia_3-OB9.jpg/960px-Peperomia_obtusifolia_3-OB9.jpg",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד."
    },
    {
        "id": 44,
        "name": "טילינדסיה (צמח אוויר)",
        "scientificName": "Tillandsia",
        "family": "ברומליים",
        "category": "אקזוטי",
        "water": 1,
        "sun": 2,
        "history": "צמחים שאינם צריכים אדמה כלל, קולטים את המים והנוטריינטים דרך העלים.",
        "uses": "עיצוב פנים תלוי, צמחי קונספט.",
        "soil": "ללא אדמה!",
        "propagation": "מוציאים חוטרים לאחר הפריחה.",
        "tip": "השרו במים למשך חצי שעה פעם בשבוע ותנו להם להתייבש הפוך לחלוטין.",
        "icon": "💨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Tillandsia_fasciculata.jpg/960px-Tillandsia_fasciculata.jpg",
        "health": "בטוח לחלוטין ואינו רעיל."
    }
];
