const plantDatabase = [
    {
        "id": 1,
        "name": "פילודנדרון פינק פרינסס",
        "scientificName": "Philodendron erubescens",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח טרופי מיערות קולומביה שזכה לפופולריות רבה בזכות עליו הוורודים.",
        "uses": "צמח נוי ביתי מבוקש מאוד.",
        "soil": "תערובת עציצים מנוקזת היטב ואוורירית.",
        "propagation": "ייחורי גבעול עם שורשי אוויר.",
        "tip": "שמרו על לחות גבוהה לקבלת צבעים עזים.",
        "icon": "🪴",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Philodendron_erubescens_-_Leaves.jpg/960px-Philodendron_erubescens_-_Leaves.jpg",
        "health": "רעיל לבליעה לחיות מחמד ובני אדם (מכיל קריסטלים של אוקסלט הסידן). מגע עם המוהל עלול לגרות את העור."
    },
    {
        "id": 2,
        "name": "מונסטרה אדנסוני (מגוונת)",
        "scientificName": "Monstera adansonii",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 2,
        "history": "ילידת מרכז ודרום אמריקה. זן נדיר עם כתמים לבנים.",
        "uses": "טיפוס על עמוד טחב או צמח משתפל.",
        "soil": "אדמה עשירה בחומר אורגני.",
        "propagation": "ייחורים במים.",
        "tip": "דורש יותר אור מזנים רגילים בשל החלקים הלבנים נטולי הכלורופיל.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Monstera_adansonii_79319231.jpg/960px-Monstera_adansonii_79319231.jpg",
        "health": "מטהר אוויר מזיהומים קלים, אך רעיל לבליעה (אוקסלט הסידן). יש להרחיק מכלבים וחתולים."
    },
    {
        "id": 3,
        "name": "ציפור גן עדן",
        "scientificName": "Strelitzia reginae",
        "family": "סטרליציים",
        "category": "נפוץ",
        "water": 3,
        "sun": 3,
        "history": "מקורו בדרום אפריקה, נקרא על שם פרחיו המזכירים ציפור צבעונית.",
        "uses": "גינון חוץ ופנים, פרחי קטיף.",
        "soil": "אדמה כבדה ועשירה.",
        "propagation": "חלוקת שורשים.",
        "tip": "צמח בוגר (בן 4-5 שנים) נדרש כדי להפריח.",
        "icon": "🌺",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Bird_of_Paradise_flower.JPG/960px-Bird_of_Paradise_flower.JPG",
        "health": "רעיל קלות לחיות מחמד במקרה של אכילת העלים או הפרחים (גורם להקאות)."
    },
    {
        "id": 4,
        "name": "ורד המדבר",
        "scientificName": "Adenium obesum",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "מקורו באזורים הצחיחים של אפריקה וחצי האי ערב.",
        "uses": "צמח בונסאי פופולרי.",
        "soil": "תערובת קקטוסים סופר-מנוקזת.",
        "propagation": "זרעים או ייחורים.",
        "tip": "היזהרו מהמוהל החלבי - הוא רעיל.",
        "icon": "🏜️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg/960px-Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg",
        "health": "רעיל מאוד! המוהל החלבי מכיל רעלנים הפוגעים בלב. השתמשו בכפפות בעת הגיזום."
    },
    {
        "id": 5,
        "name": "מימוזה ביישנית",
        "scientificName": "Mimosa pudica",
        "family": "קטניות",
        "category": "נדיר",
        "water": 3,
        "sun": 3,
        "history": "צמח מיוחד מדרום ומרכז אמריקה שעליו נסגרים במגע.",
        "uses": "צמח חינוכי לילדים וחובבי בוטניקה.",
        "soil": "אדמה לחה ומנוקזת.",
        "propagation": "זריעה מזרעים.",
        "tip": "אל תגעו בעלים יותר מדי, זה גוזל מהצמח אנרגיה.",
        "icon": "🌱",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Mimosa_pudica_in_September_month.jpg/960px-Mimosa_pudica_in_September_month.jpg",
        "health": "בטוח יחסית, אך מכיל אלקלואידים בכמויות קטנות. ברפואה המסורתית ההודית משמש לריפוי פצעים."
    },
    {
        "id": 6,
        "name": "ענב ורוד (מדינילה מרהיבה)",
        "scientificName": "Medinilla magnifica",
        "family": "מלסטומיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "אפיפיט טרופי מהפיליפינים. שימש כפרח מלכותי בבלגיה.",
        "uses": "צמח בית יוקרתי.",
        "soil": "אדמת סחלבים קלה.",
        "propagation": "ייחורים בתנאי לחות קיצוניים.",
        "tip": "צריך לחות מאוד גבוהה כדי לפרוח.",
        "icon": "🍇",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Medinilla_magnifica_flor.jpg/960px-Medinilla_magnifica_flor.jpg",
        "health": "נחשב בטוח ולא רעיל לחיות מחמד ולבני אדם."
    },
    {
        "id": 7,
        "name": "אלוורה",
        "scientificName": "Aloe vera",
        "family": "שושניים",
        "category": "נפוץ",
        "water": 1,
        "sun": 3,
        "history": "צמח עתיק ששימש תרבויות רבות למטרות רפואיות.",
        "uses": "ריפוי כוויות וטיפוח העור.",
        "soil": "תערובת קקטוסים מחולחלת.",
        "propagation": "הפרדת חוטרים.",
        "tip": "אל תשקו לעיתים קרובות, במיוחד בחורף.",
        "icon": "🌵",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/960px-Aloe_vera_flower_inset.png",
        "health": "ידוע בסגולותיו לריפוי כוויות, הרגעת העור וטיפוח. הקליפה החיצונית מכילה אלואין, שעלול להיות רעיל לחיות מחמד."
    },
    {
        "id": 8,
        "name": "פוטוס זהוב",
        "scientificName": "Epipremnum aureum",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 1,
        "history": "יליד איי שלמה, אחד מצמחי הבית העמידים ביותר.",
        "uses": "טיהור אוויר ועיצוב פנים.",
        "soil": "כל אדמת עציצים סטנדרטית.",
        "propagation": "ייחורי מים קלים במיוחד.",
        "tip": "הוא יכול לשרוד כמעט בחושך מוחלט, אך יאבד מגוונו.",
        "icon": "🍃",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Money_Plant_%28Epipremnum_aureum%29_4.jpg/960px-Money_Plant_%28Epipremnum_aureum%29_4.jpg",
        "health": "מטהר אוויר מצוין (מסנן פורמלדהיד וקסילן), אך רעיל לחיות מחמד בשל קריסטלי סידן אוקסלט."
    },
    {
        "id": 9,
        "name": "דיונאה (מלכודת זבובים)",
        "scientificName": "Dionaea muscipula",
        "family": "טלליתיים",
        "category": "טורף",
        "water": 3,
        "sun": 3,
        "history": "צמח טורף מצפון אמריקה שפיתח מנגנון לכידה אקטיבי עקב מחסור בנוטריינטים בקרקע.",
        "uses": "צמח נוי והדברת חרקים טבעית.",
        "soil": "כבול טהור מעורבב עם פרלייט.",
        "propagation": "חלוקת שורשים באביב.",
        "tip": "השתמשו רק במים מזוקקים או מי גשמים, מים רגילים יהרגו אותו.",
        "icon": "🪰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Venus_Flytrap_showing_trigger_hairs.jpg/960px-Venus_Flytrap_showing_trigger_hairs.jpg",
        "health": "בטוח לחלוטין לחיות מחמד. לא ידוע על שימושים רפואיים."
    },
    {
        "id": 10,
        "name": "כדנית",
        "scientificName": "Nepenthes",
        "family": "כדניתיים",
        "category": "טורף",
        "water": 3,
        "sun": 2,
        "history": "צמחים טרופיים בעלי מלכודות בצורת כדים המכילים נוזל עיכול.",
        "uses": "צמח בית אקזוטי ייחודי.",
        "soil": "תערובת אוורירית של ספגנום ופרלייט.",
        "propagation": "ייחורי גבעול.",
        "tip": "שמרו על לחות אוויר גבוהה מאוד סביב הכדים.",
        "icon": "🏺",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/12/N.macrophylla_x_lowii.jpg",
        "health": "בטוח לחיות מחמד. נוזל הכד שימש בעבר ברפואה העממית באסיה לטיפול בבעיות עיכול, אך לא מומלץ לשימוש מודרני."
    },
    {
        "id": 11,
        "name": "סחלב פלנופסיס",
        "scientificName": "Phalaenopsis",
        "family": "סחלביים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "הסחלב הפופולרי ביותר בעולם, יליד דרום-מזרח אסיה.",
        "uses": "צמח מתנה קלאסי לבית.",
        "soil": "תערובת קליפות עץ וטחב מיוחדת לסחלבים.",
        "propagation": "קיקי (שתילי אוויר).",
        "tip": "אל תתנו למים לעמוד בכתר העלים כדי למנוע ריקבון.",
        "icon": "🌸",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg",
        "health": "בטוח לחלוטין ולא רעיל לכלבים, חתולים וילדים."
    },
    {
        "id": 12,
        "name": "עץ הבוקן (בונסאי)",
        "scientificName": "Ficus retusa",
        "family": "תותיים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "עץ פיקוס אסיאתי המשמש רבות לאמנות הבונסאי היפנית.",
        "uses": "אמנות בונסאי ועיצוב פנים מינימליסטי.",
        "soil": "אדמת בונסאי מנקזת היטב.",
        "propagation": "ייחורים באביב.",
        "tip": "גזמו באופן קבוע כדי לשמור על צורת העץ המיניאטורי.",
        "icon": "🌳",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Ficus_retusa_herbarium_sheet.jpg/960px-Ficus_retusa_herbarium_sheet.jpg",
        "health": "המוהל החלבי עלול לגרות את העור ורעיל לבליעה לחיות מחמד."
    },
    {
        "id": 13,
        "name": "בזילקום (ריחן)",
        "scientificName": "Ocimum basilicum",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 3,
        "sun": 3,
        "history": "צמח תבלין שהגיע במקור מהודו ונהיה סימן היכר של המטבח האיטלקי.",
        "uses": "בישול, פסטו, סלטים.",
        "soil": "אדמה עשירה וקלה.",
        "propagation": "זרעים.",
        "tip": "הסירו את הפרחים ברגע שהם מופיעים כדי לשמור על טעם העלים.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Ocimum_basilicum_8zz.jpg/960px-Ocimum_basilicum_8zz.jpg",
        "health": "אנטי-בקטריאלי, עשיר בנוגדי חמצון, ויטמין K וברזל. מצוין לבריאות הלב."
    },
    {
        "id": 14,
        "name": "נענע",
        "scientificName": "Mentha",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 3,
        "sun": 2,
        "history": "צמח תבלין מרענן המשמש לחליטות מזה אלפי שנים במזרח התיכון.",
        "uses": "תה, קוקטיילים, תיבול.",
        "soil": "אדמה לחה באופן קבוע.",
        "propagation": "שלוחות שורש.",
        "tip": "מומלץ לגדל בעציץ נפרד, אחרת היא תשתלט על כל הגינה.",
        "icon": "🌱",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Mentha_spicata-IMG_6186.jpg/960px-Mentha_spicata-IMG_6186.jpg",
        "health": "מרגיע את מערכת העיכול, מקל על כאבי ראש ומיגרנות, ומשפר ריכוז."
    },
    {
        "id": 15,
        "name": "סנסיווריה (לשון החותנת)",
        "scientificName": "Sansevieria trifasciata",
        "family": "אספרגיים",
        "category": "נפוץ",
        "water": 1,
        "sun": 1,
        "history": "צמח מערב אפריקאי שנחשב לאחד מצמחי הבית החזקים ביותר.",
        "uses": "מטהר אוויר מצוין לפי מחקר של נאס\"א.",
        "soil": "תערובת קקטוסים.",
        "propagation": "חלוקה או חיתוך עלים.",
        "tip": "הדרך הכי קלה להרוג סנסיווריה היא להשקות אותה יותר מדי.",
        "icon": "🐍",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg/960px-Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg",
        "health": "מטהר אוויר מעולה, פולט חמצן בלילה (מצוין לחדרי שינה). רעיל קלות לחיות מחמד."
    },
    {
        "id": 16,
        "name": "זמיוקולקס",
        "scientificName": "Zamioculcas zamiifolia",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 1,
        "sun": 1,
        "history": "יליד מזרח אפריקה, הובא לאירופה בשנות ה-90 והפך ללהיט מיידי.",
        "uses": "צמח משרד קלאסי ומושלם למתחילים.",
        "soil": "תערובת מנוקזת היטב.",
        "propagation": "הפרדת פקעות או ייחורי עלים (תהליך איטי جدا).",
        "tip": "מעדיף הזנחה. תשקו רק כשהאדמה יבשה לחלוטין לחלוטין.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Zamioculcas_zamiifolia_1.jpg/960px-Zamioculcas_zamiifolia_1.jpg",
        "health": "רעיל לבליעה (קריסטלי אוקסלט הסידן). יש לשטוף ידיים לאחר מגע עם מוהל הצמח."
    },
    {
        "id": 17,
        "name": "קרסולה צורנית (עץ הכסף)",
        "scientificName": "Crassula ovata",
        "family": "טבוריתיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט מדרום אפריקה שנחשב כמביא מזל ועושר בפנג שואי.",
        "uses": "צמח נוי עמיד לבית ולגינה.",
        "soil": "אדמת סוקולנטים מחולחלת.",
        "propagation": "ייחורי גבעול או עלים.",
        "tip": "עליו מקבלים קצוות אדמדמים בחשיפה רבה לשמש.",
        "icon": "💰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Crassula_ovata_700.jpg",
        "health": "רעיל לכלבים וחתולים (גורם לדיכאון והקאות)."
    },
    {
        "id": 18,
        "name": "פיקוס כינורי",
        "scientificName": "Ficus lyrata",
        "family": "תותיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 3,
        "history": "עץ יער גשם מאפריקה בעל עלים גדולים בצורת כינור, פופולרי מאוד בעיצוב מודרני.",
        "uses": "צמח עציץ רצפתי דומיננטי.",
        "soil": "תערובת אוורירית ועשירה.",
        "propagation": "ייחורי אוויר.",
        "tip": "רגיש לשינויי מיקום ורוחות פרצים, העלים עלולים לנשור.",
        "icon": "🎻",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Starr_031108-0130_Ficus_lyrata.jpg/960px-Starr_031108-0130_Ficus_lyrata.jpg",
        "health": "מוהל הצמח רעיל ועלול לגרום לגירוי בעור ולבעיות עיכול אם נבלע."
    },
    {
        "id": 19,
        "name": "שרך קן-הציפור",
        "scientificName": "Asplenium nidus",
        "family": "אספלניים",
        "category": "שרך",
        "water": 3,
        "sun": 2,
        "history": "אפיפיט טרופי הגדל על צמרות עצים ויוצר צורת שושנה ענקית.",
        "uses": "צמח בית ירוק ומבריק.",
        "soil": "אדמה שומרת לחות אך לא בוצית.",
        "propagation": "נבגים (קשה מאוד בתנאי בית).",
        "tip": "אל תגעו בעלים הצעירים והרכים שצומחים מהמרכז, הם שבירים מאוד.",
        "icon": "🪹",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg/960px-Asplenium_nidus_%28Bukidnon%2C_Philippines%29_02.jpg",
        "health": "בטוח לחלוטין ולא רעיל. עוזר בהעלאת לחות האוויר בבית."
    },
    {
        "id": 20,
        "name": "אדניום כפול (ורד המדבר פרח מלא)",
        "scientificName": "Adenium obesum flore pleno",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "פיתוח בוטני מודרני מטאיוואן של ורד המדבר הקלאסי עם פרחים מלאים ועשירים.",
        "uses": "צמח אספנים מרשים.",
        "soil": "מצע קקטוסים אוורירי.",
        "propagation": "הרכבות (לשמירת גנטיקת הפרח).",
        "tip": "דורש דישון קבוע בעונת הצמיחה כדי לתמוך בפרחים הענקיים.",
        "icon": "🌹",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg/960px-Adenium_Obesum_Flower_Side_Macro_Mar22_D72_23052-58_ZS_P.jpg",
        "health": "רעיל מאוד בדומה לוורד המדבר הרגיל. הרחיקו מהישג ידם של ילדים."
    },
    {
        "id": 21,
        "name": "אגבה רכה",
        "scientificName": "Agave attenuata",
        "family": "אספרגיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "זן אגבה מקסיקני ללא קוצים, בניגוד לרוב אחיה.",
        "uses": "גינון יוקרתי, גינון יובשני.",
        "soil": "אדמה בעלת ניקוז מהיר.",
        "propagation": "חוטרים בבסיס הצמח.",
        "tip": "מושלמת לאזורים ציבוריים מכיוון שאינה דוקרת.",
        "icon": "🌵",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Agave_attenuata_001.JPG/960px-Agave_attenuata_001.JPG",
        "health": "המוהל עלול לגרות את העור ולגרום לדלקת מגע. פחות מסוכן מאגבות עם קוצים, אך עדיין דורש זהירות."
    },
    {
        "id": 22,
        "name": "מונסטרה דליציוסה",
        "scientificName": "Monstera deliciosa",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "הצמח הטרופי המפורסם בעולם, בעל העלים המחוררים שנועדו לעמוד ברוחות עזות.",
        "uses": "עיצוב פנים טרופי.",
        "soil": "מצע עציצים רגיל עם תוספת קוקוס ופרלייט.",
        "propagation": "ייחורים עם שורשי אוויר.",
        "tip": "נקו את העלים הגדולים מאבק עם מטלית לחה מדי פעם.",
        "icon": "🌴",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/960px-Monstera_deliciosa2.jpg",
        "health": "הפירות הבשלים אכילים (בטעם אננס-בננה), אך שאר חלקי הצמח רעילים לבליעה."
    },
    {
        "id": 23,
        "name": "קלתאה אורביפוליה",
        "scientificName": "Calathea orbifolia",
        "family": "מרנטתיים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 1,
        "history": "צמח טרופי מדרום אמריקה בעל עלים עגולים ענקיים עם פסים כסופים.",
        "uses": "הכנסת דרמה טרופית הביתה.",
        "soil": "אדמה שומרת לחות אך מנוקזת.",
        "propagation": "חלוקת שורשים.",
        "tip": "צמח תפילה - העלים זזים ונסגרים בלילה. רגיש מאוד ליובש ולמי ברז.",
        "icon": "🦓",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Calathea_orbifolia_2.jpg/960px-Calathea_orbifolia_2.jpg",
        "health": "בטוח לחלוטין ולא רעיל לחיות מחמד."
    },
    {
        "id": 24,
        "name": "אלוקסיה פולי",
        "scientificName": "Alocasia amazonica",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח היברידי עם עלים חצים דרמטיים דמויי פלסטיק מבריק.",
        "uses": "צמח אווירה דומיננטי.",
        "soil": "מצע תפוח ולח.",
        "propagation": "הפרדת פקעיות קטנות בשורשים.",
        "tip": "עלול להיכנס לתרדמת חורף ולהשיר את עליו, אל תזרקו - הפקעת חיה!",
        "icon": "🛡️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Alocasia_macrorrhiza_-_Val_Rahmeh_-_DSC04449.JPG/960px-Alocasia_macrorrhiza_-_Val_Rahmeh_-_DSC04449.JPG",
        "health": "רעיל מאוד לבליעה (סידן אוקסלט). גורם לנפיחות בפה ובגרון."
    },
    {
        "id": 25,
        "name": "ירקה מגוונת",
        "scientificName": "Chlorophytum comosum",
        "family": "אספרגיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "מצמחי הבית הוותיקים והאהובים ביותר. מייצר \"עכבישים\" קטנים בקצות הענפים.",
        "uses": "סלים תלויים.",
        "soil": "כל מצע יעבוד.",
        "propagation": "גזירה ושתילה של צמחי הבת (\"העכבישים\").",
        "tip": "עמיד גם בצל וגם בשמש חלקית. שורשיו הבשרניים אוגרים מים.",
        "icon": "🕷️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Hierbabuena_0611_Revised.jpg/960px-Hierbabuena_0611_Revised.jpg",
        "health": "בטוח לחלוטין לחיות מחמד. צמח מטהר אוויר מהשורה הראשונה."
    },
    {
        "id": 26,
        "name": "שפלרה מוקרנת",
        "scientificName": "Schefflera actinophylla",
        "family": "קיסוסיים",
        "category": "עץ",
        "water": 2,
        "sun": 2,
        "history": "עץ אוסטרלי המוכר גם כעץ המטרייה בגלל סידור העלים.",
        "uses": "צמח רצפה ירוק נפח.",
        "soil": "מצע עציצים בסיסי.",
        "propagation": "ייחורים או זרעים.",
        "tip": "אפשר לגזום ללא פחד כדי ליצור מראה שיחי וצפוף.",
        "icon": "☂️",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Octopus_Tree_%28Schefflera_actinophylla%29_at_Hyderabad%2C_AP_W_283.jpg",
        "health": "רעיל לחיות מחמד (עלול לגרום לגירוי חמור בפה ורעידות)."
    },
    {
        "id": 27,
        "name": "מרנטה לאוקונורה",
        "scientificName": "Maranta leuconeura",
        "family": "מרנטתיים",
        "category": "נדיר",
        "water": 3,
        "sun": 1,
        "history": "צמח קטן ומרהיב שמקפל את עליו בלילה כמו ידיים בתפילה.",
        "uses": "צמח שולחן מיוחד.",
        "soil": "אדמה עשירה בכבול.",
        "propagation": "חלוקה.",
        "tip": "דרושה לחות אוויר גבוהה. מצע יבש יגרום לקצוות העלים להשחים.",
        "icon": "🙏",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Maranta_leuconeura3.jpg",
        "health": "בטוח לחלוטין ואינו רעיל לילדים וחיות מחמד."
    },
    {
        "id": 28,
        "name": "הויה קרנוזה",
        "scientificName": "Hoya carnosa",
        "family": "הרדופיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 2,
        "history": "צמח מטפס עם עלי שעווה עבים ופרחים מדהימים שנראים כמו כוכבי חרסינה.",
        "uses": "צמח משתפל או מטפס על סורג.",
        "soil": "מצע סחלבים אוורירי.",
        "propagation": "ייחורי גבעול ממושכים.",
        "tip": "אל תגזמו את העוקץ עליו פרח הצמח - באותו מקום תופיע הפריחה הבאה.",
        "icon": "⭐",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg/960px-NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg",
        "health": "בטוח לחלוטין ואינו רעיל."
    },
    {
        "id": 29,
        "name": "סטפנוטיס",
        "scientificName": "Stephanotis floribunda",
        "family": "הרדופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "יליד מדגסקר, ידוע בפרחיו הלבנים והריחניים המשמשים בזרות כלה.",
        "uses": "מטפס ריחני לבית ולמרפסת.",
        "soil": "אדמה מנקזת עשירה.",
        "propagation": "ייחורים למחצה-מעוצים.",
        "tip": "הפרחים מפיצים ריח יסמין חזק במיוחד בערב.",
        "icon": "👰",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/31/Stephanotis_floribunda3L._Marie.jpg",
        "health": "בטוח לגידול בסביבת חיות מחמד וילדים."
    },
    {
        "id": 30,
        "name": "בגוניה מנוקדת",
        "scientificName": "Begonia maculata",
        "family": "בגוניים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח פוטוגני להפליא עם עלים בצורת כנף מלאך מנוקדים בנקודות כסף.",
        "uses": "צמח אספנים מעוצב.",
        "soil": "מצע עשיר שומר לחות.",
        "propagation": "ייחורי גבעול במים (מושרשים בקלות).",
        "tip": "מעדיף עציץ מעט צפוף ומים רק כשהחצי העליון של האדמה יבש.",
        "icon": "🎨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/df/Begonia_maculata3073316230.jpg",
        "health": "השורשים רעילים מאוד לחיות מחמד, גם העלים מכילים רעלנים המגרים את הפה."
    },
    {
        "id": 31,
        "name": "פיטוניה (צמח העצבים)",
        "scientificName": "Fittonia albivenis",
        "family": "קוציציים",
        "category": "נפוץ",
        "water": 3,
        "sun": 1,
        "history": "צמח זוחל מיערות פרו המוכר ברשת העורקים הלבנה או האדומה על עליו.",
        "uses": "טרריומים וגינות בקבוק.",
        "soil": "אדמה שומרת לחות קבועה.",
        "propagation": "ייחורים קטנים.",
        "tip": "מתעלף בדרמטיות כשהוא צמא, אך יחזור לעצמו במהירות לאחר השקיה.",
        "icon": "🧠",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Colpfl25.jpg/960px-Colpfl25.jpg",
        "health": "בטוח לחלוטין לחיות מחמד וילדים."
    },
    {
        "id": 32,
        "name": "פילאה פפרומיואידס",
        "scientificName": "Pilea peperomioides",
        "family": "סרפדיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח הפנקייק הסיני שכבש את העולם, קל לגידול ומתרבה במהירות.",
        "uses": "עציץ חלון מתוק לחלוקה לחברים.",
        "soil": "מצע עציצים רגיל.",
        "propagation": "מוציא אינספור פקעיות סביב צמח האם.",
        "tip": "סובבו את העציץ פעם בשבוע כדי שיגדל ישר ולא ייטה לכיוון השמש.",
        "icon": "🥞",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pilea_peperomioides_Chinese_money_plant.jpg/960px-Pilea_peperomioides_Chinese_money_plant.jpg",
        "health": "בטוח לחלוטין ולא רעיל."
    },
    {
        "id": 33,
        "name": "פלטיצריום (קרן האייל)",
        "scientificName": "Platycerium",
        "family": "פוליפודיים",
        "category": "שרך",
        "water": 2,
        "sun": 2,
        "history": "שרך אפיפיט יוצא דופן שעליו נראים כמו קרני אייל מפוצלות.",
        "uses": "תלייה על קירות כמיצג אמנות חי.",
        "soil": "טחב ספגנום לח, לעיתים מוצמד ללוח עץ.",
        "propagation": "חלוקת חוטרים בוגרים.",
        "tip": "השקו את הצמח דרך העלה המגן הבסיסי התחתון ולא ישירות על הקרניים.",
        "icon": "🦌",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Platycerium_bifurcatum.jpg/960px-Platycerium_bifurcatum.jpg",
        "health": "בטוח ואינו רעיל."
    },
    {
        "id": 34,
        "name": "טללית",
        "scientificName": "Drosera",
        "family": "טלליתיים",
        "category": "טורף",
        "water": 3,
        "sun": 3,
        "history": "צמח טורף עדין בעל זרועות דביקות המכוסות בטיפות המדמות טל.",
        "uses": "הדברת ברחשים וחרקים קטנים.",
        "soil": "מצע כבול.",
        "propagation": "זרעים קטנים או ייחורי עלים.",
        "tip": "כמו הדיונאה - רק מים מזוקקים ואור שמש חזק מאוד.",
        "icon": "💧",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Drosera_spatulata_KansaiHabit.jpg/960px-Drosera_spatulata_KansaiHabit.jpg",
        "health": "בטוח לחיות מחמד. ברפואה העממית שימש לטיפול בשיעול וברונכיט בשל חומרים מכייחים."
    },
    {
        "id": 35,
        "name": "פיקוס גומי",
        "scientificName": "Ficus elastica",
        "family": "תותיים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "עץ הודי חזק שבעבר הפיקו ממנו גומי טבעי.",
        "uses": "צמח רצפה גבוה לבית ולמשרד.",
        "soil": "מצע סטנדרטי מנוקז.",
        "propagation": "ייחורים.",
        "tip": "הזן השחור (Burgundy) צריך פחות אור, הזן המגוון (Tineke) צריך יותר.",
        "icon": "🌲",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Ficus_elastica_leaves_02.JPG/960px-Ficus_elastica_leaves_02.JPG",
        "health": "המוהל הלבן (לייטקס) עלול לגרום לאלרגיות קשות בעור ולגירוי בעיניים."
    },
    {
        "id": 36,
        "name": "ליטופס (אבנים חיות)",
        "scientificName": "Lithops",
        "family": "חיעדיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט מדהים מדרום אפריקה שהתפתח להיראות כמו חלוקי נחל כדי להימנע מטורפים.",
        "uses": "אוסף מיוחד על אדן החלון.",
        "soil": "100% תערובת אבנים פומיס עם מעט מאוד חומר אורגני.",
        "propagation": "זרעים זעירים.",
        "tip": "משירים את עליהם פעם בשנה. בתקופה זו חל איסור מוחלט להשקות.",
        "icon": "🪨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Marloth-Lithops-drawing.jpg/960px-Marloth-Lithops-drawing.jpg",
        "health": "בטוח ואינו רעיל לחיות מחמד (אך חיות עלולות לאכול אותם בטעות כי הם נראים כמו אבנים)."
    },
    {
        "id": 37,
        "name": "טרדסקנטיה (יהודי נודד)",
        "scientificName": "Tradescantia zebrina",
        "family": "קומליניים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח משתפל עמיד בטירוף, עם עלים בגווני כסף וסגול נוצצים.",
        "uses": "סלים תלויים וצמח קל למתחילים.",
        "soil": "כל אדמה תתאים.",
        "propagation": "ייחורים פשוט משתרשים בכל מגע עם מים או אדמה.",
        "tip": "צבעו הסגול יהיה חזק יותר ככל שיקבל יותר אור (אך לא שמש ישירה קופחת).",
        "icon": "🌌",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Zebrina_pendula_20060521_2_closer.jpg",
        "health": "המוהל עלול לגרום לגירוי בעור אצל כלבים וחתולים במגע מתמשך."
    },
    {
        "id": 38,
        "name": "סטפליה (פרח הכוכב המסריח)",
        "scientificName": "Stapelia gigantea",
        "family": "הרדופיים",
        "category": "נדיר",
        "water": 1,
        "sun": 3,
        "history": "סוקולנט קקטוס-לכאורה מדרום אפריקה שפורח בפרח ענק דמוי כוכב פרוותי.",
        "uses": "לאספנים הרפתקנים.",
        "soil": "תערובת קקטוסים.",
        "propagation": "ייחורי גבעול.",
        "tip": "הפרח מפיץ ריח של בשר רקוב כדי למשוך זבובים מאביקים.",
        "icon": "🌟",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Stapelia_gigantea00.jpg/960px-Stapelia_gigantea00.jpg",
        "health": "בטוח ואינו רעיל (הריח הרע מהפרח אינו מזיק בריאותית)."
    },
    {
        "id": 39,
        "name": "רוזמרין",
        "scientificName": "Rosmarinus officinalis",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 1,
        "sun": 3,
        "history": "שיח ים-תיכוני ארומטי בעל היסטוריה ארוכה ברפואה ובקולינריה.",
        "uses": "בישול בשרים, תפוחי אדמה, גדר חיה.",
        "soil": "אדמה גירית מנוקזת, עמיד לבצורת.",
        "propagation": "ייחורים חצי-מעוצים.",
        "tip": "לא אוהב עציצים קטנים לאורך זמן. חייב שמש מלאה בחוץ.",
        "icon": "🌿",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rosemary_in_bloom.JPG/960px-Rosemary_in_bloom.JPG",
        "health": "משפר זיכרון, אנטי-דלקתי, עשיר בנוגדי חמצון ומסייע לעיכול."
    },
    {
        "id": 40,
        "name": "עגבניית שרי",
        "scientificName": "Solanum lycopersicum var. cerasiforme",
        "family": "סולניים",
        "category": "ירק",
        "water": 3,
        "sun": 3,
        "history": "זן מתוק וקטן של עגבניה, שמקורו בדרום אמריקה וכיום פופולרי בגידול ביתי.",
        "uses": "סלטים ונשנוש ישר מהשיח.",
        "soil": "אדמה עשירה ודשנה מאוד.",
        "propagation": "זרעים.",
        "tip": "שתלו עמוק באדמה - הצמח מגדל שורשים לאורך כל הגבעול שקבור.",
        "icon": "🍅",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/960px-Tomato_je.jpg",
        "health": "הפרי בריא מאוד (מכיל ליקופן). העלים והגבעולים רעילים לאכילה (מכילים סולנין)."
    },
    {
        "id": 41,
        "name": "תות שדה",
        "scientificName": "Fragaria × ananassa",
        "family": "ורדיים",
        "category": "ירק",
        "water": 3,
        "sun": 3,
        "history": "הכלאה בוטנית של תותי בר מצפון ודרום אמריקה שנוצרה בצרפת.",
        "uses": "קינוחים וגידול מהנה לילדים.",
        "soil": "אדמה לחה ומנוקזת, רצוי לכסות בחיפוי קש.",
        "propagation": "שלוחות.",
        "tip": "הרחיקו את הפירות מאדמה לחה כדי שלא ירקבו.",
        "icon": "🍓",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/03/103_Fragaria_vesca_L.jpg",
        "health": "עשיר בוויטמין C ונוגדי חמצון. בטוח לחלוטין."
    },
    {
        "id": 42,
        "name": "ויקטוריה רג׳יה",
        "scientificName": "Victoria amazonica",
        "family": "נופריים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 3,
        "history": "שושנת המים הגדולה בעולם מהאמזונס, עליה יכולים לשאת משקל של ילד.",
        "uses": "בריכות נוי גדולות וגנים בוטניים.",
        "soil": "אדמה בוצית בקרקעית בריכה מחוממת.",
        "propagation": "זרעים בתנאים מיוחדים.",
        "tip": "הפרח פורח בלילה, לבן ביום הראשון וורוד ביום השני.",
        "icon": "🪷",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Victoria_amazonica_edit_1.jpg/960px-Victoria_amazonica_edit_1.jpg",
        "health": "הזרעים שימשו בעבר למאכל על ידי ילידים. הצמח עצמו מוגן בקוצים חדים כתער מתחת לעלים."
    },
    {
        "id": 43,
        "name": "עץ האהבה (אפרומיה)",
        "scientificName": "Peperomia obtusifolia",
        "family": "פלפליים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "דומה מאוד לפילאה אך עליו עבים וכהים יותר, מגיע מיערות הגשם בפלורידה והקריביים.",
        "uses": "צמח שולחן קומפקטי וסימפטי.",
        "soil": "אדמת עציצים מתנקזת.",
        "propagation": "ייחורי עלה או גבעול.",
        "tip": "האויב מספר 1 שלו הוא השקיית יתר.",
        "icon": "💚",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Peperomia_obtusifolia_3-OB9.jpg/960px-Peperomia_obtusifolia_3-OB9.jpg",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד."
    },
    {
        "id": 44,
        "name": "טילינדסיה (צמח אוויר)",
        "scientificName": "Tillandsia",
        "family": "ברומליים",
        "category": "אקזוטי",
        "water": 1,
        "sun": 2,
        "history": "צמחים שאינם צריכים אדמה כלל, קולטים את המים והנוטריינטים דרך העלים.",
        "uses": "עיצוב פנים תלוי, צמחי קונספט.",
        "soil": "ללא אדמה!",
        "propagation": "מוציאים חוטרים לאחר הפריחה.",
        "tip": "השרו במים למשך חצי שעה פעם בשבוע ותנו להם להתייבש הפוך לחלוטין.",
        "icon": "💨",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Tillandsia_fasciculata.jpg/960px-Tillandsia_fasciculata.jpg",
        "health": "בטוח לחלוטין ואינו רעיל."
    },
    {
        "name": "ספטיפילום (ליליית השלום)",
        "scientificName": "Spathiphyllum",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 3,
        "sun": 1,
        "history": "צמח טרופי מיבשת אמריקה, סמל לשלום בזכות פרחיו הלבנים הדומים לדגל לבן.",
        "uses": "מטהר אוויר מצוין לחללים סגורים, סופח נבגי עובש.",
        "soil": "אדמה לחה ומנוקזת היטב.",
        "propagation": "חלוקת שורשים.",
        "tip": "עליו נופלים בדרמטיות כשחסר לו מים, אך יזדקפו מיד לאחר השקיה.",
        "icon": "🏳️",
        "health": "רעיל קלות לחיות מחמד וילדים (גורם לגירוי בפה בשל קריסטלי סידן אוקסלט).",
        "id": 45,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Spathiphyllum_cochlearispathum_RTBG.jpg/960px-Spathiphyllum_cochlearispathum_RTBG.jpg"
    },
    {
        "name": "סינגוניום",
        "scientificName": "Syngonium podophyllum",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח מטפס מיערות הגשם של מקסיקו וברזיל שמשנה את צורת עליו בבגרותו.",
        "uses": "צמח בית משתפל קל מאוד לגידול.",
        "soil": "תערובת עציצים סטנדרטית.",
        "propagation": "ייחורים במים.",
        "tip": "ניתן לאלף אותו לטפס על עמוד טחב או לתת לו להשתפל למטה.",
        "icon": "🌿",
        "health": "רעיל לבליעה לכלבים וחתולים (סידן אוקסלט).",
        "id": 46,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Zingiber_malaysianum.jpg/960px-Zingiber_malaysianum.jpg"
    },
    {
        "name": "דקל החדרים (חמדוריאה)",
        "scientificName": "Chamaedorea elegans",
        "family": "דקליים",
        "category": "עץ",
        "water": 2,
        "sun": 1,
        "history": "דקל קטן יליד מקסיקו שהפך סמל סטטוס בטרקלינים ויקטוריאניים במאה ה-19.",
        "uses": "הכנסת אווירה טרופית עדינה וקלאסית לבית.",
        "soil": "אדמת עציצים קלה עם ניקוז.",
        "propagation": "זריעה מזרעים (תהליך ממושך).",
        "tip": "רגיש לעודף דשן, השתמשו בחצי מהכמות המומלצת.",
        "icon": "🌴",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד וילדים.",
        "id": 47,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Chamaedorea_elegans_Mart.JPG/960px-Chamaedorea_elegans_Mart.JPG"
    },
    {
        "name": "אנטוריום (פרח הפלמינגו)",
        "scientificName": "Anthurium andraeanum",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח טרופי מקולומביה שמתהדר בפרחים אדומים ומבריקים (מתחלפים) דמויי פלסטיק.",
        "uses": "מתנה יוקרתית וצמח בית פורח.",
        "soil": "תערובת סחלבים או תערובת מנוקזת מאוד.",
        "propagation": "חלוקת שורשים באביב.",
        "tip": "אוהב לחות גבוהה - רססו את העלים במים, אך לא את הפרחים עצמם.",
        "icon": "❤️",
        "health": "רעיל לחיות מחמד (גירוי עור ובליעה בשל סידן אוקסלט).",
        "id": 48,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/AnthuriumAndraenum.jpg/960px-AnthuriumAndraenum.jpg"
    },
    {
        "name": "דרצנה מרגינטה (עץ הדרקון)",
        "scientificName": "Dracaena marginata",
        "family": "אספרגיים",
        "category": "עץ",
        "water": 2,
        "sun": 2,
        "history": "עץ פיסולי ממדגסקר בעל עלים צרים עם שוליים אדומים-סגולים.",
        "uses": "צמח רצפתי גבוה שמוסיף קווים אנכיים לחלל.",
        "soil": "תערובת מנוקזת.",
        "propagation": "ייחורי גזע עליונים.",
        "tip": "קצוות עלים חומים מעידים בדרך כלל על יובש באוויר או מליחות במים.",
        "icon": "🐉",
        "health": "רעיל לכלבים וחתולים (מכיל ספונינים הגורמים להקאות וחולשה).",
        "id": 49,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Dracaena_reflexa.JPG/960px-Dracaena_reflexa.JPG"
    },
    {
        "name": "לבנדר (אזוביון)",
        "scientificName": "Lavandula",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 1,
        "sun": 3,
        "history": "צמח ים-תיכוני קלאסי, שימש כבר בימי הרומאים לבישום מי רחצה.",
        "uses": "הפקת שמנים אתריים, בישום, מרגיע מתחים, דוחה יתושים.",
        "soil": "אדמה גירית מאוד מנוקזת.",
        "propagation": "ייחורים או זריעה.",
        "tip": "זקוק לשמש ישירה ולזרימת אוויר. אל תשקו את העלים עצמם.",
        "icon": "🪻",
        "health": "שמן הלבנדר מרגיע ומסייע לשינה, אך לעיסת הצמח רעילה לכלבים וחתולים.",
        "id": 50,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Single_lavender_flower02.jpg/960px-Single_lavender_flower02.jpg"
    },
    {
        "name": "חמנייה",
        "scientificName": "Helianthus annuus",
        "family": "מורכבים",
        "category": "נפוץ",
        "water": 3,
        "sun": 3,
        "history": "תורבתה במקור על ידי ילידים באמריקה הצפונית לפני אלפי שנים והפכה לגידול חקלאי עולמי.",
        "uses": "הפקת שמן, גרעיני מאכל, פרחי נוי קייציים.",
        "soil": "אדמה עמוקה ועשירה.",
        "propagation": "זריעה ישירה באביב.",
        "tip": "הפרחים עוקבים אחרי תנועת השמש בשמיים (הליו-טרופיזם).",
        "icon": "🌻",
        "health": "בטוח לחלוטין ואינו רעיל. עשיר בויטמין E.",
        "id": 51,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sunflower_sky_backdrop.jpg/960px-Sunflower_sky_backdrop.jpg"
    },
    {
        "name": "בוגנוויליה",
        "scientificName": "Bougainvillea",
        "family": "ניקטאגיניים",
        "category": "עץ",
        "water": 1,
        "sun": 3,
        "history": "שיח מטפס דרום-אמריקאי הקרוי על שם אדמירל צרפתי, המוכר בזכות עליו הצבעוניים (חפים).",
        "uses": "גינון חוץ, כיסוי חומות, פרגולות.",
        "soil": "עמיד למגוון קרקעות.",
        "propagation": "ייחורי גזע.",
        "tip": "כדי לעודד פריחה, יש לתת לצמח \"לסבול\" מעט ממחסור במים ולהימנע מעודף דשן חנקני.",
        "icon": "🌺",
        "health": "הקוצים עלולים לגרום לזיהום ודלקת מגע, העלים רעילים קלות לחיות מחמד.",
        "id": 52,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bougainvillea_closeup.jpg/960px-Bougainvillea_closeup.jpg"
    },
    {
        "name": "רקפת מצויה",
        "scientificName": "Cyclamen persicum",
        "family": "רקפתיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 1,
        "history": "פרח בר מזרח-תיכוני שהפך לאחד מצמחי העציץ הפורחים הנמכרים בעולם בחורף.",
        "uses": "צמח פורח לחלונות ולמרפסות מוצלות בחורף.",
        "soil": "אדמה קרירה ולחה מעט.",
        "propagation": "זרעים.",
        "tip": "השקו רק מתחתית העציץ (צלוחית), מים על פקעת הרקפת יגרמו לריקבונה.",
        "icon": "🌷",
        "health": "פקעת הרקפת רעילה מאוד לחיות מחמד (גורמת להקאות וקשיי נשימה).",
        "id": 53,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Yagur_%E2%80%93_Nesher%2C_the_Green_Path_%E2%80%93_Mount_Carmel_016.JPG/960px-Yagur_%E2%80%93_Nesher%2C_the_Green_Path_%E2%80%93_Mount_Carmel_016.JPG"
    },
    {
        "name": "פיקוס בנימינה",
        "scientificName": "Ficus benjamina",
        "family": "תותיים",
        "category": "עץ",
        "water": 2,
        "sun": 2,
        "history": "עץ טרופי מדרום אסיה שהפך לעץ רחוב וצמח משרד פופולרי בשל נופו הבוכה.",
        "uses": "עץ רצפה עשיר עלים בתוך הבית.",
        "soil": "תערובת מנקזת עשירה בחומר אורגני.",
        "propagation": "ייחורים.",
        "tip": "הצמח שונא שינויים! הזזת העציץ או שינוי תאורה יגרמו לנשירת עלים מסיבית עד שיתאקלם.",
        "icon": "🌳",
        "health": "מוהל הצמח מכיל לייטקס שעלול לגרום לאלרגיה וגירוי בעור. רעיל לחיות מחמד.",
        "id": 54,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_%2824823189861%29.jpg/960px-Starr-080608-7576-Ficus_benjamina-habit_with_Laysan_albatross-Gym_Sand_Island-Midway_Atoll_%2824823189861%29.jpg"
    },
    {
        "name": "שרך בוסטון",
        "scientificName": "Nephrolepis exaltata",
        "family": "פוליפודיים",
        "category": "שרך",
        "water": 3,
        "sun": 1,
        "history": "מוטציה טבעית שהתגלתה במשלוח לבוסטון ב-1894 והפכה לשרך הבית הנפוץ בעולם.",
        "uses": "צמח תלוי קלאסי המעניק מראה יער עשיר.",
        "soil": "אדמת כבול לחה באופן קבוע.",
        "propagation": "חלוקת שורשים או שלוחות.",
        "tip": "זקוק ללחות אוויר קבועה, מומלץ למקם בחדר רחצה מואר.",
        "icon": "🌿",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד וילדים.",
        "id": 55,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/30/Boston_Fern_%282873392811%29.png"
    },
    {
        "name": "ציקאס",
        "scientificName": "Cycas revoluta",
        "family": "ציקסיים",
        "category": "אקזוטי",
        "water": 1,
        "sun": 2,
        "history": "מאובן חי! צמח פרהיסטורי שהיה קיים עוד בתקופת הדינוזאורים.",
        "uses": "עיצוב נוף דרמטי וגינון טרופי עמיד.",
        "soil": "קרקע סופר מנוקזת, עדיפות לחולית.",
        "propagation": "חוטרים מבסיס הגזע.",
        "tip": "גדל באיטיות קיצונית - מוציא דור עלים אחד בלבד בשנה.",
        "icon": "🦕",
        "health": "רעיל ביותר! כל חלקי הצמח ובמיוחד הזרעים מכילים ציקסין שגורם לכשל כבדי קטלני בכלבים.",
        "id": 56,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Cycas_inflorescence.jpg"
    },
    {
        "name": "סחלב דנדרוביום",
        "scientificName": "Dendrobium",
        "family": "סחלביים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "סוג סחלב עצום בגודלו, יליד אוסטרליה ואסיה, הגדל בטבע על גזעי עצים וסלעים.",
        "uses": "צמח מתנה, קישוט יוקרתי לבית.",
        "soil": "תערובת קליפות עץ גסה.",
        "propagation": "ייחורי גבעול (קייקי).",
        "tip": "זקוק לתקופת קרירות ויובש בחורף כדי לפרוח באביב.",
        "icon": "🌸",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד וילדים.",
        "id": 57,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/09/Dendrobium-kingianum.jpg"
    },
    {
        "name": "קקטוס זיגזג (אפיפילום)",
        "scientificName": "Epiphyllum anguliger",
        "family": "צבריים",
        "category": "קקטוס",
        "water": 2,
        "sun": 2,
        "history": "קקטוס יער אפיפיטי ממקסיקו, המוכר בזכות גבעוליו הפחוסים דמויי זיגזג (או עצם של דג).",
        "uses": "סלים תלויים מרהיבים.",
        "soil": "תערובת קקטוסים מועשרת במעט קומפוסט.",
        "propagation": "ייחורי גבעול.",
        "tip": "בניגוד לקקטוסים מדבריים, הוא אוהב לחות ומעדיף שמש מסוננת ולא ישירה קופחת.",
        "icon": "🌵",
        "health": "בטוח לחלוטין ואינו רעיל.",
        "id": 58,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/47/Epiphyllum_anguliger1Emma_Lindahl.jpg"
    },
    {
        "name": "טימין (קורנית)",
        "scientificName": "Thymus vulgaris",
        "family": "שפתניים",
        "category": "תבלין",
        "water": 1,
        "sun": 3,
        "history": "שימש את המצרים הקדמונים לחניטה ואת היוונים כקטורת במקדשים.",
        "uses": "תיבול בשרים, תבשילים, ותה נגד שיעול.",
        "soil": "אדמה גירית וענייה עם ניקוז מעולה.",
        "propagation": "ייחורים או חלוקה.",
        "tip": "הקפידו לא להשקות יותר מדי - טימין שונא \"רגליים רטובות\".",
        "icon": "🌿",
        "health": "מצוין לבריאות, מכיל רכיבים אנטי-בקטריאליים חזקים (תימול). בטוח לשימוש.",
        "id": 59,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Thymus_vulgaris1.JPG"
    },
    {
        "name": "פילודנדרון ביפינטיפידיום",
        "scientificName": "Philodendron bipinnatifidum",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 2,
        "history": "צמח טרופי גדול בעל עלים מפוצלים עמוקות, יליד דרום אמריקה.",
        "uses": "צמח נוי גדול ומרשים לגינות מוצלות ולבתים מרווחים.",
        "soil": "אדמה עשירה בחומר אורגני.",
        "propagation": "חוטרים או זרעים.",
        "tip": "מפתח שורשי אוויר ארוכים מאוד - אפשר להפנות אותם חזרה לאדמה או לתת להם להשתלשל.",
        "icon": "🍃",
        "health": "רעיל לבליעה לכלבים וחתולים (מכיל קריסטלי סידן אוקסלט).",
        "id": 60,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Tree1.JPG"
    },
    {
        "name": "לילי פריז (הוסטה)",
        "scientificName": "Hosta",
        "family": "אספרגיים",
        "category": "נפוץ",
        "water": 3,
        "sun": 1,
        "history": "צמח צל קלאסי מיפן וסין, תורבת רבות בשל עליו הרחבים והמרשימים.",
        "uses": "גינון חוץ באזורים מוצלים לחלוטין.",
        "soil": "אדמה לחה ועשירה בקומפוסט.",
        "propagation": "חלוקת גושים באביב.",
        "tip": "האויב מספר אחד של ההוסטה הם חלזונות ושבלולים - שמרו עליה מפניהם!",
        "icon": "🐌",
        "health": "העלים רעילים לבליעה לכלבים, סוסים וחתולים (מכילים ספונינים).",
        "id": 61,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Hosta_Bressingham_Blue.JPG/960px-Hosta_Bressingham_Blue.JPG"
    },
    {
        "name": "עץ הלימון",
        "scientificName": "Citrus limon",
        "family": "פיגמיים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "מקורו בצפון מזרח הודו, הובא לאירופה בתקופת רומא העתיקה.",
        "uses": "פרי מאכל, קוסמטיקה, חומרי ניקוי טבעיים.",
        "soil": "אדמה עשירה ומנוקזת, אוהב דשן ברזל.",
        "propagation": "הרכבה (לרוב) או ייחורים.",
        "tip": "רגיש מאוד לקור - באזורים קרים מומלץ לגדל בעציץ ולהכניס פנימה בחורף.",
        "icon": "🍋",
        "health": "הפרי בריא מאוד (ויטמין C), אך עלי העץ והשמנים האתריים רעילים לכלבים וחתולים.",
        "id": 62,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/960px-P1030323.JPG"
    },
    {
        "name": "אווירנית דמוית-אזוב (טחב ספרדי)",
        "scientificName": "Tillandsia usneoides",
        "family": "ברומליים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "צמח אפיפיטי חסר שורשים הגדל על ענפי עצים בדרום ארצות הברית, יוצר מראה של \"זקן סבא\".",
        "uses": "עיצוב פנים תלוי, חיפוי לעציצי סחלבים.",
        "soil": "ללא אדמה כלל.",
        "propagation": "חלוקת הגוש.",
        "tip": "יש לרסס במים 2-3 פעמים בשבוע או להטביל בקערת מים פעם בשבוע.",
        "icon": "🌫️",
        "health": "בטוח לחלוטין ואינו רעיל.",
        "id": 63,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Spanish_moss_at_the_Mcbryde_Garden_in_hawaii.jpg/960px-Spanish_moss_at_the_Mcbryde_Garden_in_hawaii.jpg"
    },
    {
        "name": "קלדיום דו-גוני",
        "scientificName": "Caladium bicolor",
        "family": "לופיים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 1,
        "history": "צמח פקעת מיערות האמזונס, המפיק עלים מרהיבים בשילובי אדום, ורוד, ירוק ולבן.",
        "uses": "צמחייה צבעונית לאזורי צל בקיץ.",
        "soil": "תערובת לחה ועשירה בכבול.",
        "propagation": "חלוקת פקעיות באביב.",
        "tip": "בחורף הצמח מאבד את עליו ונכנס לתרדמת - יש להפסיק להשקות ולאחסן את הפקעת עד האביב.",
        "icon": "🎨",
        "health": "רעיל ביותר לחיות מחמד ובני אדם (סידן אוקסלט). גורם לנפיחות וכאב חמור בפה.",
        "id": 64,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Caladium_bicolor_2.jpg/960px-Caladium_bicolor_2.jpg"
    },
    {
        "name": "פילודנדרון מלינקו (פילודנדרון זהוב)",
        "scientificName": "Philodendron hederaceum var. oxycardium",
        "family": "לופיים",
        "category": "נפוץ",
        "water": 2,
        "sun": 1,
        "history": "אחד מצמחי הבית הנפוצים ביותר, קל מאוד לגידול ובעל עלי לב חמודים.",
        "uses": "סלים תלויים ומדפים צרים.",
        "soil": "מצע עציצים בסיסי.",
        "propagation": "ייחורים במים (משתרש מהר מאוד).",
        "tip": "ניתן לגזום אותו בחופשיות כדי ליצור מראה צפוף ועבות יותר.",
        "icon": "💚",
        "health": "רעיל לחיות מחמד (קריסטלי סידן אוקסלט).",
        "id": 65,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Philodendron_scandens_subsp_oxycardium2.jpg"
    },
    {
        "name": "קקטוס חבית (אכינוקקטוס)",
        "scientificName": "Echinocactus",
        "family": "צבריים",
        "category": "קקטוס",
        "water": 1,
        "sun": 3,
        "history": "קקטוס כדורי וקוצני מאוד ממקסיקו, יכול לחיות מעל 100 שנים בטבע.",
        "uses": "גינות סלעים, אוספי קקטוסים.",
        "soil": "תערובת מינרלית חולית עם ניקוז מהיר מאוד.",
        "propagation": "זרעים.",
        "tip": "כמעט ואין צורך להשקותו בחורף. השקיית יתר היא הגורם המרכזי לתמותתו.",
        "icon": "🛢️",
        "health": "אינו רעיל, אך הקוצים החזקים שלו מהווים סכנה פיזית משמעותית לחיות ולילדים.",
        "id": 66,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Echinocactus_platyacanthus._Jard%C3%ADn_de_Cactus_-_Lanzarote_-_J07.jpg/960px-Echinocactus_platyacanthus._Jard%C3%ADn_de_Cactus_-_Lanzarote_-_J07.jpg"
    },
    {
        "name": "עץ הפיסטוק (אלת הבוטנה)",
        "scientificName": "Pistacia vera",
        "family": "אלתיים",
        "category": "עץ",
        "water": 1,
        "sun": 3,
        "history": "מקורו באסיה התיכונה ובמזרח התיכון. הזרעים (פיסטוקים) נאכלו עוד מהתקופה הפלאוליתית.",
        "uses": "פירות מאכל יוקרתיים וטעימים.",
        "soil": "אדמה חולית ומנוקזת היטב.",
        "propagation": "הרכבה על כנות של אלת המסטיק.",
        "tip": "עץ דו-ביתי: כדי לקבל פרי, חייבים לשתול עץ זכר ועץ נקבה קרובים זה לזה.",
        "icon": "🥜",
        "health": "האגוזים בטוחים ובריאים מאוד, אך העלים רעילים קלות לכלבים, סוסים וחתולים.",
        "id": 67,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pistachio_vera.jpg/960px-Pistachio_vera.jpg"
    },
    {
        "name": "באובב",
        "scientificName": "Adansonia",
        "family": "חלמיתיים",
        "category": "עץ",
        "water": 1,
        "sun": 3,
        "history": "עץ אפריקאי איקוני המכונה \"עץ החיים\", אוגר כמויות אדירות של מים בגזעו העבה ויכול לחיות אלפי שנים.",
        "uses": "פירות מאכל סופר-פוד, חומרי גלם, וצל במדבר.",
        "soil": "אדמה חולית ומנוקזת.",
        "propagation": "זרעים.",
        "tip": "מתאים לגידול רק בגינות עצומות, שכן שורשיו והגזע שלו מתנפחים לממדים אדירים.",
        "icon": "🌳",
        "health": "בטוח לחלוטין ואינו רעיל, הפרי עשיר בויטמין C.",
        "id": 68,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Baobab_Adansonia_digitata.jpg/960px-Baobab_Adansonia_digitata.jpg"
    },
    {
        "name": "דקל תמר",
        "scientificName": "Phoenix dactylifera",
        "family": "דקליים",
        "category": "עץ",
        "water": 2,
        "sun": 3,
        "history": "מהעצים המתורבתים העתיקים בעולם, בעל משמעות דתית ותרבותית עמוקה במזרח התיכון.",
        "uses": "פירות מתוקים, סכך, חומרי בנייה.",
        "soil": "אדמה עמוקה עם מי תהום או השקיה סדירה בקיץ.",
        "propagation": "חוטרים מהבסיס (כדי להבטיח את זן הפרי).",
        "tip": "רק דקל תמר נקבה מניב פרי, ויש להאביק אותו באופן ידני מפרחי עץ זכר.",
        "icon": "🌴",
        "health": "העץ בטוח לחלוטין. קוצי כפות התמר בבסיס העלה מסוכנים פיזית ועלולים לגרום לזיהום בדקירה.",
        "id": 69,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dates005.jpg/960px-Dates005.jpg"
    },
    {
        "name": "קראסולה מקדש הבודהה",
        "scientificName": "Crassula Buddhas Temple",
        "family": "טבוריתיים",
        "category": "סוקולנט",
        "water": 1,
        "sun": 2,
        "history": "הכלאה מיוחדת של שני מיני קראסולה דרום-אפריקאים, שנוצרה ב-1959. העלים מסודרים בגיאומטריה מופלאה.",
        "uses": "צמח אספנים מיניאטורי לחלון מואר.",
        "soil": "100% תערובת קקטוסים גרגרית מחולחלת.",
        "propagation": "ייחורי גזע.",
        "tip": "רגיש מאוד להשקיית יתר או מים שתקועים בין העלים - השקו רק מהתחתית.",
        "icon": "⛩️",
        "health": "רעיל קלות לחיות מחמד במקרה של בליעה משמעותית (גורם להקאות).",
        "id": 70,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Crassula_capitella_2.jpg/960px-Crassula_capitella_2.jpg"
    },
    {
        "name": "סחלב וניל",
        "scientificName": "Vanilla planifolia",
        "family": "סחלביים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 2,
        "history": "סחלב מטפס מקסיקני המפיק את תרמילי הוניל האמיתיים. האצטקים השתמשו בו לתיבול שוקולד.",
        "uses": "הפקת תמצית וניל אמיתית (אחד התבלינים היקרים בעולם).",
        "soil": "מצע סחלבים אוורירי, זקוק לעמוד תמיכה לטיפוס.",
        "propagation": "ייחורי גזע.",
        "tip": "בגידול ביתי, חייבים להאביק את הפרח ידנית בדיוק בבוקר בו הוא נפתח, אחרת לא יתפתח תרמיל.",
        "icon": "🍦",
        "health": "בטוח לחלוטין לגידול בקרבת חיות מחמד, השרף יכול לגרום לגירוי קל בעור רגיש.",
        "id": 71,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Vanilla_planifolia_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-278.jpg"
    },
    {
        "name": "פלפל רפאים (קרולינה ריפר)",
        "scientificName": "Capsicum chinense Carolina Reaper",
        "family": "סולניים",
        "category": "תבלין",
        "water": 2,
        "sun": 3,
        "history": "הפלפל החריף בעולם (לשעבר), פותח בקרוליינה הדרומית. מכיל חריפות של למעלה מ-1.5 מיליון סקוביל.",
        "uses": "בישול אקסטרים, רטבים חריפים (בזהירות!).",
        "soil": "אדמה עשירה ודשנה, שמש מלאה.",
        "propagation": "זרעים (נובטים בטמפרטורה גבוהה).",
        "tip": "חובה להשתמש בכפפות כשקוטפים את הפרי או נוגעים בזרעים.",
        "icon": "🌶️",
        "health": "הפרי בוער ויכול לגרום לכוויות כימיות אמיתיות בעיניים או בבליעה ללא הכנה. העלים רעילים לאכילה.",
        "id": 72,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Carolina_Reaper_pepper_pods_%28cropped%29.jpg/960px-Carolina_Reaper_pepper_pods_%28cropped%29.jpg"
    },
    {
        "name": "עגבנייה שחורה (אינדיגו רוז)",
        "scientificName": "Solanum lycopersicum Indigo Rose",
        "family": "סולניים",
        "category": "ירק",
        "water": 3,
        "sun": 3,
        "history": "זן עגבנייה שפותח באוניברסיטת אורגון כדי להכיל כמויות עצומות של אנתוציאנינים (נוגדי החמצון שיש באוכמניות).",
        "uses": "סלטים מיוחדים, גידול מרשים בגינת ירק.",
        "soil": "אדמה עשירה קומפוסט, השקיה סדירה.",
        "propagation": "זרעים.",
        "tip": "הצבע השחור מופיע רק היכן שהשמש נוגעת בקליפה. החלק המוצל יישאר ירוק-אדום.",
        "icon": "🍅",
        "health": "הפרי בטוח ובריא מאוד. העלים והגבעולים רעילים לאכילה (סולנין).",
        "id": 73,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Starr_020323-0062_Solanum_seaforthianum.jpg/960px-Starr_020323-0062_Solanum_seaforthianum.jpg"
    },
    {
        "name": "צמח הטורף (סרצניה)",
        "scientificName": "Sarracenia",
        "family": "סרצניים",
        "category": "טורף",
        "water": 3,
        "sun": 3,
        "history": "צמח טורף צפון אמריקאי בעל מלכודות קנקן גבוהות וצבעוניות שלוכדות חרקים פסיביות.",
        "uses": "צמח חוץ מרשים לביצות נוי והדברת חרקים בגינה.",
        "soil": "כבול טהור מעורבב עם פרלייט.",
        "propagation": "חלוקת קנה השורש.",
        "tip": "חייב להיות בחוץ בשמש ישירה וחייב תקופת תרדמת קרה בחורף כדי לשרוד את השנה הבאה.",
        "icon": "🏺",
        "health": "בטוח לחלוטין לילדים וחיות מחמד. לא רעיל.",
        "id": 74,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Sarracenia_ne1.JPG/960px-Sarracenia_ne1.JPG"
    },
    {
        "name": "לוטוס הודי (נלומבו)",
        "scientificName": "Nelumbo nucifera",
        "family": "נלומביים",
        "category": "אקזוטי",
        "water": 3,
        "sun": 3,
        "history": "הפרח הקדוש ביותר באסיה, מסמל טוהר מכיוון שהוא צומח מתוך הבוץ אך עליו ופרחיו נשארים נקיים לחלוטין.",
        "uses": "בריכות נוי גדולות, פקעות וזרעים למאכל באסיה.",
        "soil": "אדמה כבדה/בוצית בקרקעית של מאגר מים מתוקים.",
        "propagation": "ייחורי קנה שורש באביב.",
        "tip": "עלי הלוטוס דוחים מים ברמה הפיזיקלית (אפקט הלוטוס) - המים מתגלגלים מהם כמו פנינים.",
        "icon": "🪷",
        "health": "בטוח לחלוטין. רוב חלקי הצמח נאכלים במסורת האסייתית.",
        "id": 75,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sacred_lotus_Nelumbo_nucifera.jpg/960px-Sacred_lotus_Nelumbo_nucifera.jpg"
    },
    {
        "name": "ציפורן החתול",
        "scientificName": "Dianthus caryophyllus",
        "family": "ציפורניים",
        "category": "נפוץ",
        "water": 2,
        "sun": 3,
        "history": "פרח ים-תיכוני עתיק. היוונים והרומאים השתמשו בו לזרים וכתרים בגלל הריח התבליני שלו, שמזכיר את תבלין הציפורן.",
        "uses": "פרחי קטיף, עציצים פורחים למרפסת.",
        "soil": "אדמה גירית, מנקזת, רצוי מעט בסיסית.",
        "propagation": "ייחורים, זרעים.",
        "tip": "הסירו פרחים נבולים בקביעות כדי לעודד המון פרחים חדשים לאורך העונה.",
        "icon": "🌸",
        "health": "העלים רעילים קלות לכלבים וחתולים (גורמים להקאות וגירוי עור קל).",
        "id": 76,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3b/W_carnation4051.jpg"
    },
    {
        "name": "ברומליה פספסית (גוסמניה)",
        "scientificName": "Guzmania",
        "family": "ברומליים",
        "category": "אקזוטי",
        "water": 2,
        "sun": 1,
        "history": "צמח יער גשם אפיפיטי מדרום אמריקה. מפתח תפרחת כוכב מרשימה בצבעים עזים.",
        "uses": "מתנה טרופית מצוינת לעיצוב הבית והמשרד.",
        "soil": "תערובת סחלבים אוורירית לחלוטין.",
        "propagation": "הפרדת חוטרים שצומחים מהבסיס לאחר פריחת צמח האם.",
        "tip": "משקים אותה דרך \"כוס\" העלים המרכזית ולא ישירות לאדמה!",
        "icon": "🍍",
        "health": "בטוח לחלוטין ואינו רעיל לחיות מחמד (בטוח לחתולים ללעוס).",
        "id": 77,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/80/DirkvdM_red-white-stripe_flower.jpg"
    },
    {
        "name": "עץ שקדים (שקד מצוי)",
        "scientificName": "Prunus dulcis",
        "family": "ורדיים",
        "category": "עץ",
        "water": 1,
        "sun": 3,
        "history": "מקורו במזרח התיכון, מהעצים הראשונים לפרוח בארץ ישראל ומסמל את חג הט\"ו בשבט בפריחתו הלבנה-ורדרדה.",
        "uses": "ייצור שקדים, מרציפן, שמנים קוסמטיים, גינון ופריחה.",
        "soil": "גדל כמעט בכל קרקע מנוקזת, עמיד מאוד ליובש וגיר.",
        "propagation": "הרכבה על כנות של שקד בר או אפרסק.",
        "tip": "זקוק למנות קור בחורף כדי לפרוח באביב. רוב הזנים צריכים עץ מזן אחר להאבקה.",
        "icon": "🌸",
        "health": "שקדים מתוקים בטוחים ובריאים מאוד. שקדים מרים (מזני בר) ועלי העץ מכילים אמיגדלין, שמתפרק לציאניד ורעילים לבליעה.",
        "id": 78,
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/960px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg"
    }
];
